export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';
export const SAVE_MY_NAME = 'SAVE_MY_NAME';
export const LOAD_COURSES = 'LOAD_COURSES';
export const LOAD_COUSRSES_SUCCESS = 'LOAD_COUSRSES_SUCCESS';
export const LOAD_AUTHOR_SUCCESS = 'LOAD_AUTHOR_SUCCESS';
export const UPDATE_COUSRSES_SUCCESS = 'UPDATE_COUSRSES_SUCCESS';
export const ADD_COUSRSES_SUCCESS = 'ADD_COUSRSES_SUCCESS';
